# Generated by Django 5.2.8 on 2025-12-11 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_contactmessage_usertelegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
